development:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: car_parts_platform_development

test:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: car_parts_platform_test
# config/cable.yml
production:
  adapter: redis
  url: <%= ENV['REDISCLOUD_URL'] %>
  channel_prefix: car_parts_platform_production
  