development:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: car_parts_platform_development

test:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: car_parts_platform_test
production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: car_parts_platform_production
  