:queues:
  - default

:scheduler:
  :schedule:
    publish_scheduled_posts:
      cron: "0 0 * * *" # Runs every day at midnight
      class: "PublishScheduledPostsJob"
    cancel_orders:
      cron: "0 0 * * *" # Runs every day at midnight
      class: "CancelOrdersJob"
